WHENEVER SQLERROR EXIT;

SET ECHO ON;

set define off;

CREATE OR REPLACE PACKAGE ASD.REPORTE_MIGRACION_PKG IS

  PROCEDURE P_REPORTE_MIGRACION(REPORTE_MIGRACION OUT SYS_REFCURSOR,
                                L_TELEFONOS TELEFONOS_TBL_TYP);
                                
  PROCEDURE P_REPORTE_VENTA_MIGRACION(REPORTE_VENTA_MIGRACION OUT SYS_REFCURSOR,
                                      L_TELEFONOS TELEFONOS_TBL_TYP);

END REPORTE_MIGRACION_PKG;
/

CREATE OR REPLACE PACKAGE BODY ASD.REPORTE_MIGRACION_PKG IS

  PROCEDURE P_REPORTE_MIGRACION(REPORTE_MIGRACION OUT SYS_REFCURSOR,
                                L_TELEFONOS TELEFONOS_TBL_TYP)
    IS
    TYPE SRC_REPORTE_MIGRACION IS REF CURSOR;
    REPORTE SRC_REPORTE_MIGRACION;
    BEGIN
      OPEN REPORTE_MIGRACION FOR 
         SELECT * FROM (SELECT   
         (SELECT TO_CHAR(MAX(AOH.ENTRY_DATE),'DD/MM/YYYY HH24:MI:SS')   
         FROM ASD.ASD_ORDER_HISTORY  AOH   
         WHERE AOH.ID_STATUS = 14   
         AND  AOH.ORDER_ID = ACO.ORDER_ID) FECHA,  
         UPPER(TRIM(ACO.REGIONAL_FF)) FULFILLMENT, ACO.PREFIX PREFIJO,ACO.FOLIO FOLIO , ACO.SUFFIX SUFIJO , ACO.ORDER_ID CONSECUTIVO, ACO.CUSTCODE CUENTA ,     
         TRANSLATE(ACO.LEGAL_NAME,'|',' ') RAZON_SOCIAL,ACO.INVOICE_NUM NUM_FACTURA, AD.QUANTITY CANTIDAD_RADIOS,  
         CASE    
         WHEN ADDE.SIM IS NULL AND ADDE.IMEI IS NOT NULL THEN 'C'   
         WHEN ADDE.SIM IS NOT NULL AND ADDE.IMEI IS NULL THEN 'S'   
         WHEN ADDE.SIM IS NOT NULL AND ADDE.IMEI IS NOT NULL THEN 'M'   
         WHEN ADDE.SIM IS NULL AND ADDE.IMEI IS NULL THEN 'N/A'    
         END AS CSM,  
         TRANSLATE(ADDE.MODEL,'|',' ') MODELO, 
         TRANSLATE(ADA.RATE_PLAN_NAME,'|', ' ') PLAN, 
         TRANSLATE(ACO.COURIER_DESC,'|',' ') MENSAJERIA,  
         AOS.DESCRIPTION ESTATUS,  
         (SELECT TO_CHAR(MAX(AOH.ENTRY_DATE),'DD/MM/YYYY HH24:MI:SS')    
         FROM ASD.ASD_ORDER_HISTORY  AOH   
         WHERE AOH.ID_STATUS = 17   
         AND  AOH.ORDER_ID = ACO.ORDER_ID) FECHA_SALIDA_RUTA,  
         ROUND((SELECT MAX(AOH.ENTRY_DATE)    
         FROM ASD.ASD_ORDER_HISTORY  AOH   
         WHERE AOH.ID_STATUS = 17   
         AND  AOH.ORDER_ID = ACO.ORDER_ID) -  (SELECT MAX(AOH.ENTRY_DATE)    
         FROM ASD.ASD_ORDER_HISTORY  AOH     
         WHERE AOH.ID_STATUS = 14    
         AND  AOH.ORDER_ID = ACO.ORDER_ID),5) DIAS_TRANSCURRIDOS,  
         (SELECT TO_CHAR(MAX(AOH.ENTRY_DATE),'DD/MM/YYYY HH24:MI:SS')    
         FROM ASD.ASD_ORDER_HISTORY  AOH   
         WHERE AOH.ID_STATUS IN (21,22)   
         AND  AOH.ORDER_ID = ACO.ORDER_ID) FIN_ORDEN,  
         TRANSLATE(ACORC.DESCRIPTION,'|',' ') MOTIVO_CANCELACION, TRANSLATE(ACOR.DESCRIPTION,'|',' ') SUBMOTIVO_CANCELACION,    
         'MIGRACION' TIPO, 
          ACR.DATE_VISIT_1 FECHA_VISITA_1,   
          TRANSLATE(TRANSLATE (TRANSLATE (TRANSLATE (ACR.RESOLUTION_VISIT_1, '|', ' '), CHR(13), ' '), CHR(10), ' '), CHR (09),  ' ')  RESULTADO_VISITA_1,   
          TRANSLATE(TRANSLATE (TRANSLATE (TRANSLATE (ACR.COMMENTS, '|', ' '), CHR(13), ' '), CHR(10), ' '), CHR (09),  ' ')  OBSERVACIONES_VISITA_1,     
          ACR.DATE_VISIT_2 FECHA_VISITA_2,   
          TRANSLATE(TRANSLATE (TRANSLATE (TRANSLATE (ACR.RESOLUTION_VISIT_2, '|', ' '), CHR(13), ' '), CHR(10), ' '), CHR (09),  ' ')  RESULTADO_VISITA_2,   
          TRANSLATE(TRANSLATE (TRANSLATE (TRANSLATE (ACR.COMMENTS_2, '|', ' '), CHR(13), ' '), CHR(10), ' '), CHR (09),  ' ')  OBSERVACIONES_VISITA_2,    
          ACR.DATE_VISIT_3 FECHA_VISITA_3,   
          TRANSLATE(TRANSLATE (TRANSLATE (TRANSLATE (ACR.RESOLUTION_VISIT_3, '|', ' '), CHR(13), ' '), CHR(10), ' '), CHR (09),  ' ')  RESULTADO_VISITA_3,   
          TRANSLATE(TRANSLATE (TRANSLATE (TRANSLATE (ACR.COMMENTS_3, '|', ' '), CHR(13), ' '), CHR(10), ' '), CHR (09),  ' ') OBSERVACIONES_VISITA_3    
         FROM  ASD.ASD_CONTRACT_ORDER ACO   
         LEFT JOIN ASD.ASD_DEVICE_ACC ADA ON ADA.ORDER_ID = ACO.ORDER_ID 
         LEFT JOIN ASD.ASD_DEVICE  AD ON AD.ORDER_ID = ACO.ORDER_ID  
         LEFT JOIN ASD.ASD_ORDER_STATUS AOS ON AOS.ID = ACO.STATUS   
         LEFT JOIN ASD.ASD_DEVICE_DETAIL  ADDE ON ADDE.DEVICE_ID = AD.DEVICE_ID  
         LEFT JOIN ASD.ASD_REASON AR ON AR.ORDER_ID = ACO.ORDER_ID   
         LEFT JOIN ASD.ASD_CAT_ORD_RRC ACORC ON AR.REASON_ID = ACORC.ORD_RRC_ID    
         LEFT JOIN ASD.ASD_CAT_ORD_RR ACOR ON  ACOR.ORD_RRC_ID = ACORC.ORD_RRC_ID  
         LEFT JOIN ASD.ASD_COURIER_REGISTER ACR ON ACO.ORDER_ID = ACR.ORDER_ID  
         WHERE  
         (ACO.ORDER_FLOW  IS NULL OR ACO.ORDER_FLOW = 'DF') 
          AND ADDE.MSISDN IN  (SELECT COLUMN_VALUE
					   FROM TABLE( L_TELEFONOS ))
         ORDER BY ACO.ORDER_ID DESC  ) 
         WHERE TRUNC(TO_DATE(FECHA,'DD/MM/YYYY HH24:MI:SS')) BETWEEN TRUNC(SYSDATE-60) AND TRUNC(SYSDATE);

   
    END;
  
  PROCEDURE P_REPORTE_VENTA_MIGRACION(REPORTE_VENTA_MIGRACION OUT SYS_REFCURSOR,
                                     L_TELEFONOS TELEFONOS_TBL_TYP)
    IS
  BEGIN
          OPEN REPORTE_VENTA_MIGRACION FOR 
         SELECT * FROM  (SELECT DISTINCT  
  (SELECT TO_CHAR(MAX(AOH.ENTRY_DATE),'DD/MM/YYYY HH24:MI:SS')  
  FROM ASD.ASD_ORDER_HISTORY  AOH  
  WHERE AOH.ID_STATUS = 14  
  AND  AOH.ORDER_ID = ACO.ORDER_ID) FECHA, 
  UPPER(TRIM(ACO.REGIONAL_FF)) FULFILLMENT, ACO.PREFIX PREFIJO,ACO.FOLIO FOLIO , ACO. SUFFIX SUFIJO , ACO.ORDER_ID CONSECUTIVO, ACO.CUSTCODE CUENTA ,    
  TRANSLATE(ACO.LEGAL_NAME,'|',' ') RAZON_SOCIAL,ACO.INVOICE_NUM NUM_FACTURA, AD.QUANTITY CANTIDAD_RADIOS, 
  CASE   
  WHEN ADDE.SIM IS NULL AND ADDE.IMEI IS NOT NULL THEN 'C'  
  WHEN ADDE.SIM IS NOT NULL AND ADDE.IMEI IS NULL THEN 'S'  
  WHEN ADDE.SIM IS NOT NULL AND ADDE.IMEI IS NOT NULL THEN 'M'  
  WHEN ADDE.SIM IS NULL AND ADDE.IMEI IS NULL THEN 'N/A'   
  END AS CSM, 
  TRANSLATE(ACO.COURIER_DESC,'|',' ') MENSAJERIA, 
  AOS.DESCRIPTION ESTATUS, 
  (SELECT TO_CHAR(MAX(AOH.ENTRY_DATE),'DD/MM/YYYY HH24:MI:SS')   
  FROM ASD.ASD_ORDER_HISTORY  AOH  
    WHERE AOH.ID_STATUS = 17  
  AND  AOH.ORDER_ID = ACO.ORDER_ID) FECHA_SALIDA_RUTA, 
  ROUND((SELECT MAX(AOH.ENTRY_DATE)   
  FROM ASD.ASD_ORDER_HISTORY  AOH  
  WHERE AOH.ID_STATUS = 17  
  AND  AOH.ORDER_ID = ACO.ORDER_ID) -  (SELECT MAX(AOH.ENTRY_DATE)   
  FROM ASD.ASD_ORDER_HISTORY  AOH    
    WHERE AOH.ID_STATUS = 14   
  AND  AOH.ORDER_ID = ACO.ORDER_ID),5) DIAS_TRANSCURRIDOS, 
  (SELECT TO_CHAR(MAX(AOH.ENTRY_DATE),'DD/MM/YYYY HH24:MI:SS')   
  FROM ASD.ASD_ORDER_HISTORY  AOH  
  WHERE AOH.ID_STATUS IN (21,22)  
  AND  AOH.ORDER_ID = ACO.ORDER_ID) FIN_ORDEN, 
  TRANSLATE(ACORC.DESCRIPTION,'|',' ') MOTIVO_CANCELACION,TRANSLATE(ACOR.DESCRIPTION,'|',' ') SUBMOTIVO_CANCELACION,  
  'MIGRACION' TIPO 
  FROM  ASD.ASD_CONTRACT_ORDER ACO  
  LEFT JOIN ASD.ASD_DEVICE  AD ON AD.ORDER_ID = ACO.ORDER_ID LEFT JOIN ASD.ASD_ORDER_STATUS AOS ON AOS.ID = ACO.STATUS  
  LEFT JOIN ASD.ASD_DEVICE_DETAIL  ADDE ON ADDE.DEVICE_ID = AD.DEVICE_ID LEFT JOIN ASD.ASD_REASON AR ON AR.ORDER_ID = ACO.ORDER_ID  
  LEFT JOIN ASD.ASD_CAT_ORD_RRC ACORC ON AR.REASON_ID = ACORC.ORD_RRC_ID   
  LEFT JOIN ASD.ASD_CAT_ORD_RR ACOR ON  ACOR.ORD_RRC_ID = ACORC.ORD_RRC_ID  
  WHERE  
     (ACO.ORDER_FLOW  IS NULL OR ACO.ORDER_FLOW = 'DF') 
   AND ADDE.MSISDN IN (SELECT COLUMN_VALUE
					   FROM TABLE( L_TELEFONOS ))
  GROUP BY  UPPER(TRIM(ACO.REGIONAL_FF)), ACO.PREFIX, TRIM(ACO.REGIONAL_FF), ACO.FOLIO, ACO.ORDER_ID, ACO.CUSTCODE,  
  ACO.LEGAL_NAME, ACO.INVOICE_NUM, ACO.SUFFIX, AD.QUANTITY,  
  CASE WHEN ADDE.SIM IS NULL AND ADDE.IMEI IS NOT NULL THEN 'C' WHEN ADDE.SIM IS NOT NULL AND ADDE.IMEI IS NULL THEN 'S'  
  WHEN ADDE.SIM IS NOT NULL AND ADDE.IMEI IS NOT NULL THEN 'M' WHEN ADDE.SIM IS NULL AND ADDE.IMEI IS NULL THEN 'N/A' END,  
  ACO.COURIER_DESC, AOS.DESCRIPTION,ACORC.DESCRIPTION ,ACOR.DESCRIPTION  
  ORDER BY ACO.ORDER_ID DESC ) 
  WHERE TRUNC(TO_DATE(FECHA,'DD/MM/YYYY HH24:MI:SS')) BETWEEN TRUNC(SYSDATE-30) AND TRUNC(SYSDATE);

  END;
 
  
END REPORTE_MIGRACION_PKG;
/

WHENEVER SQLERROR CONTINUE
